# Generated by Django 5.2.1 on 2026-06-03 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Base Resume', max_length=255)),
                ('raw_text', models.TextField(help_text='Сюда вставляется исходный текст резюме')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TailoredApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_description', models.TextField(help_text='Текст вакансии, под которую адаптируем')),
                ('tailored_resume_text', models.TextField(blank=True, help_text='Адаптированный текст резюме', null=True)),
                ('cover_letter', models.TextField(blank=True, help_text='Сгенерированное сопроводительное письмо', null=True)),
                ('missing_keywords', models.JSONField(blank=True, help_text='Список ключевых слов, которых не хватало', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Processing'), ('SUCCESS', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='head.resume')),
            ],
        ),
    ]
